    2023.08.11(금) quest
- 분석 대상 : 
성별,신장,심혈관질환,체중,흡연여부,연령,직업,혈액형,재발여부
- 단일 변수 chart 각각 작성
- 이상치와 결측치가 없는 데이터셋 만들기
- option : 연령이 중앙값~Q3 범위 속한 인원 수 찾기

In [1]:
import pandas as pd

In [2]:
df_ROS = pd.read_csv('../../datasets/RecurrenceofSurgery.csv')
df_ROS.head(2)

,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,0,1PT,22.8,3,51.0,0.0,0,0,0,0,...,3,51.6,36.6,14.4,0,-1.01,2048.5,4,Down,0
1,1,2PT,44.9,4,26.0,0.0,0,0,0,0,...,0,40.8,7.2,17.8,0,-1.14,1753.1,4,Up,0

In [3]:
df_ROS.columns

Index(['Unnamed: 0', '환자ID', 'Large Lymphocyte', 'Location of herniation',
       'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수', '당뇨여부', '말초동맥질환여부', '빈혈여부',
       '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환', '암발병여부', '연령', '우울증여부', '입원기간',
       '입원일자', '종양진행여부', '직업', '체중', '퇴원일자', '헤모글로빈수치', '혈전합병증여부', '환자통증정도',
       '흡연여부', '통증기간(월)', '수술기법', '수술시간', '수술실패여부', '수술일자', '재발여부', '혈액형',
       '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도', 'Instability', 'MF + ES',
       'Modic change', 'PI', 'PT', 'Seg Angle(raw)', 'Vaccum disc', '골밀도',
       '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증'],
      dtype='object')

In [4]:
df_ROS_forpatient = df_ROS[['성별','신장', '심혈관질환','체중','흡연여부', '연령', '직업', '혈액형', '재발여부']]
#df_ROS_forpatient.head(2)
df_ROS_forpatient.tail(5)

      성별   신장  심혈관질환    체중  흡연여부  연령   직업    혈액형  재발여부
1889   2  157      0  64.0     0  59   무직   RH+A     0
1890   2  157      0  59.0     0  42  사무직   RH+B     0
1891   1  167      0  70.0     0  61   무직   RH+O     0
1892   1  177      0  77.0     0  29  사무직   RH+A     0
1893   2  168      0  49.0     0  30  사무직  RH+AB     0

In [5]:
df_ROS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1894 entries, 0 to 1893
Data columns (total 52 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1894 non-null   int64
 1   환자ID                    1894 non-null   object
 2   Large Lymphocyte        1894 non-null   float64
 3   Location of herniation  1894 non-null   int64
 4   ODI                     462 non-null    float64
 5   가족력                     1843 non-null   float64
 6   간질성폐질환                  1894 non-null   int64
 7   고혈압여부                   1894 non-null   int64
 8   과거수술횟수                  1894 non-null   int64
 9   당뇨여부                    1894 non-null   int64
 10  말초동맥질환여부                1894 non-null   int64
 11  빈혈여부                    1894 non-null   int64
 12  성별                      1894 non-null   int64
 13  스테로이드치료                 1894 non-null   int64
 14  신부전여부                   1894 non-null   int64
 15  신장                      1894 non-null   int64
 16  심혈관질환                   1894 non-null   int64
 17  암발병여부                   1894 non-null   int64
 18  연령                      1894 non-null   int64
 19  우울증여부                   1894 non-null   int64
 20  입원기간                    1894 non-null   int64
 21  입원일자                    1894 non-null   int64
 22  종양진행여부                  1894 non-null   int64
 23  직업                      1479 non-null   object
 24  체중                      1894 non-null   float64
 25  퇴원일자                    1894 non-null   int64
 26  헤모글로빈수치                 1893 non-null   float64
 27  혈전합병증여부                 1894 non-null   int64
 28  환자통증정도                  1894 non-null   int64
 29  흡연여부                    1894 non-null   int64
 30  통증기간(월)                 1890 non-null   float64
 31  수술기법                    1813 non-null   object
 32  수술시간                    1840 non-null   float64
 33  수술실패여부                  1894 non-null   int64
 34  수술일자                    1894 non-null   int64
 35  재발여부                    1894 non-null   int64
 36  혈액형                     1894 non-null   object
 37  전방디스크높이(mm)             1894 non-null   float64
 38  후방디스크높이(mm)             1894 non-null   float64
 39  지방축적도                   1891 non-null   float64
 40  Instability             1894 non-null   int64
 41  MF + ES                 1894 non-null   float64
 42  Modic change            1894 non-null   int64
 43  PI                      1890 non-null   float64
 44  PT                      1890 non-null   float64
 45  Seg Angle(raw)          1893 non-null   float64
 46  Vaccum disc             1894 non-null   int64
 47  골밀도                     998 non-null    float64
 48  디스크단면적                  1893 non-null   float64
 49  디스크위치                   1894 non-null   int64
 50  척추이동척도                  1894 non-null   object
 51  척추전방위증                  1894 non-null   int64
dtypes: float64(16), int64(31), object(5)
memory usage: 769.6+ KB

In [6]:
df_ROS.isnull()

,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1890,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1891,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1892,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1893,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [7]:
df_ROS_drops = df_ROS.dropna()
df_ROS_drops.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 162 entries, 0 to 1216
Data columns (total 52 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              162 non-null    int64
 1   환자ID                    162 non-null    object
 2   Large Lymphocyte        162 non-null    float64
 3   Location of herniation  162 non-null    int64
 4   ODI                     162 non-null    float64
 5   가족력                     162 non-null    float64
 6   간질성폐질환                  162 non-null    int64
 7   고혈압여부                   162 non-null    int64
 8   과거수술횟수                  162 non-null    int64
 9   당뇨여부                    162 non-null    int64
 10  말초동맥질환여부                162 non-null    int64
 11  빈혈여부                    162 non-null    int64
 12  성별                      162 non-null    int64
 13  스테로이드치료                 162 non-null    int64
 14  신부전여부                   162 non-null    int64
 15  신장                      162 non-null    int64
 16  심혈관질환                   162 non-null    int64
 17  암발병여부                   162 non-null    int64
 18  연령                      162 non-null    int64
 19  우울증여부                   162 non-null    int64
 20  입원기간                    162 non-null    int64
 21  입원일자                    162 non-null    int64
 22  종양진행여부                  162 non-null    int64
 23  직업                      162 non-null    object
 24  체중                      162 non-null    float64
 25  퇴원일자                    162 non-null    int64
 26  헤모글로빈수치                 162 non-null    float64
 27  혈전합병증여부                 162 non-null    int64
 28  환자통증정도                  162 non-null    int64
 29  흡연여부                    162 non-null    int64
 30  통증기간(월)                 162 non-null    float64
 31  수술기법                    162 non-null    object
 32  수술시간                    162 non-null    float64
 33  수술실패여부                  162 non-null    int64
 34  수술일자                    162 non-null    int64
 35  재발여부                    162 non-null    int64
 36  혈액형                     162 non-null    object
 37  전방디스크높이(mm)             162 non-null    float64
 38  후방디스크높이(mm)             162 non-null    float64
 39  지방축적도                   162 non-null    float64
 40  Instability             162 non-null    int64
 41  MF + ES                 162 non-null    float64
 42  Modic change            162 non-null    int64
 43  PI                      162 non-null    float64
 44  PT                      162 non-null    float64
 45  Seg Angle(raw)          162 non-null    float64
 46  Vaccum disc             162 non-null    int64
 47  골밀도                     162 non-null    float64
 48  디스크단면적                  162 non-null    float64
 49  디스크위치                   162 non-null    int64
 50  척추이동척도                  162 non-null    object
 51  척추전방위증                  162 non-null    int64
dtypes: float64(16), int64(31), object(5)
memory usage: 67.1+ KB

In [8]:
df_ROS_drops.describe()

,Unnamed: 0,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,말초동맥질환여부,...,MF + ES,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추전방위증
count,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.0,...,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000
mean,392.512346,40.742593,2.549383,30.611111,0.086420,0.024691,0.067901,0.216049,0.055556,0.0,...,2060.549568,0.314815,45.619136,16.054938,15.231111,0.030864,-1.536790,1979.197222,3.962963,0.012346
std,298.997959,13.136057,0.919441,10.817084,0.281854,0.155664,0.252356,0.531249,0.229772,0.0,...,526.440930,0.743270,9.676375,8.592999,13.892825,0.173486,0.498315,320.372075,0.367785,0.110766
min,0.000000,6.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,1021.000000,0.000000,14.000000,1.500000,-1.800000,0.000000,-2.740000,1209.500000,2.000000,0.000000
25%,111.500000,31.800000,2.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,1704.000000,0.000000,39.525000,9.650000,9.050000,0.000000,-1.815000,1753.100000,4.000000,0.000000
50%,472.000000,42.800000,3.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,2012.850000,0.000000,44.700000,14.200000,13.650000,0.000000,-1.520000,1970.700000,4.000000,0.000000
75%,573.500000,48.175000,3.000000,37.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,2409.350000,0.000000,51.600000,20.400000,19.900000,0.000000,-1.262500,2155.300000,4.000000,0.000000
max,1216.000000,89.000000,5.000000,68.000000,1.000000,1.000000,1.000000,3.000000,1.000000,0.0,...,3755.400000,3.000000,76.200000,48.700000,165.000000,1.000000,1.400000,3088.000000,5.000000,1.000000

In [9]:
df_ROS_drops.describe(include=object)

       환자ID   직업  수술기법   혈액형  척추이동척도
count   162  162   162   162     162
unique  162   16     2     4       4
top     1PT  사무직  TELD  RH+A  Middle
freq      1   53   155    58      94

In [10]:
df_ROS_drops['직업'].value_counts()

사무직      53
자영업      19
주부       15
노동직      11
학생       10
군인       10
운수업       7
의료직       7
사업가       6
농업        6
교사        5
무직        4
운동선수      3
공무원       3
특수전문직     2
예술가       1
Name: 직업, dtype: int64

In [ ]:
sns.df_TOCC_dropna = df_ROS.dropna()
df_TOCC_dropna.info()

In [11]:
sns.countplot(data=df_ROS_drops, x='혈액형')
plt.show()

NameError: name 'sns' is not defined

In [ ]:
sns.countplot(data=df_ROS, x='성별')
plt.show()

In [ ]:
sns.histplot(data=df_ROS_drops, x='신장')
plt.show()

In [ ]:
sns.countplot(data=df_ROS_drops, x='심혈관질환')
plt.show()

In [ ]:
sns.histplot(data=df_ROS, x='체중')
plt.show()

In [ ]:
sns.histplot(data=df_ROS, x='흡연여부')
plt.show()

In [ ]:
sns.histplot(data=df_ROS, x='연령')
plt.show()

In [ ]:
sns.histplot(data=df_ROS_drops, x='혈액형')
plt.show()

In [ ]:
sns.countplot(data=df_ROS_drops, x='재발여부')
plt.show()

In [ ]:
sns.boxplot(data=df_ROS_drops, x='연령')
plt.show()

In [ ]:

df_ROS_drops['연령'].value_counts()

In [ ]:
Q1 = df_ROS_drops['연령'].describe()['25%']
Q3 = df_ROS_drops['연령'].describe()['75%']
IQR = Q3 - Q1

In [ ]:
bound_up = Q3 + 1.5 * IQR
bound_low = Q1 - 1.5 * IQR
bound_low,bound_up

In [ ]:
condition = (df_ROS_drops['연령'] <= bound_up) #긍정 조건 변환
condition

In [ ]:
df_ROS_condition = df_ROS_drops[condition]

In [ ]:
sns.boxplot(data=df_ROS_condition, x='연령')
plt.show()